const {Plant} = require('../models')

const plantData = [
    
    {
        id: 1,
        common_name: "Aloe Vera",
        latin_name: "Aloe vera",
        watering_schedule: "Only When the Soil is Dry (1-3 Weeks)",
        soil_type: "A Well-Draining Potting Mix is Required",
        light_req: "Lots of Direct Sunlight",
        fertilizer_req: "Only Once a Season",
        space_req: "Requires Sufficient Space for Frequent Propagation",
        indoor_outdoor: "indoor",
        pest_info: "Common Pests: Red Spider Mites, Mealybugs, Snoutbeetles, and Gallmites",
        pet_care: "This Plant Can be Poisonious for Both Cats and Dogs When Consumed", 
        user_id: null
    }, 
    {
        id:2,
        common_name: "Begonia",
        latin_name: "genus Begonia", 
        watering_schedule: "Only When the Soil Begins to Dry Out (Approx. Once a Week)",
        soil_type: "Use Light Potting Soil With Extra Perlite",
        light_req: "Needs Bright and Indirect Sunlight",
        fertilizer_req: "Only When Growing and Flowering (Approx. Once a Month",
        space_req: "Most Stay Within the Average Size of Their Initial Placement",
        indoor_outdoor: "indoor",
        pest_info: "Common Pests: Spider Mites, Mealybugs, Thrips, Scales, Snails, and Slugs",
        pet_care: "Undergrowth Can Be Toxic to Most Pets When Consumed",
        user_id: null
    },
    {
        id: 3,
        common_name: "Bird of Paradise",
        latin_name: "Strelitzia Reginae", 
        watering_schedule: "When the Top Layer of the Soil Becomes Dry",
        soil_type: "Needs a Slightly Acidic to Neutral Potting Mix",
        light_req: "Needs Bright Light and Some Direct Sunlight",
        fertilizer_req: "About Once a Month, No Feeding in the Winter",
        space_req: "Will Grow Very Tall Instead of Spread Out",
        indoor_outdoor: "indoor",
        pest_info: "Common Pests: Spider Mites, Mealybugs, and Scales",
        pet_care: "Mildly Toxic to Cats and Dogs in Stem, Root, and Flower Areas", 
        user_id: null
    },
    {
        id: 4, 
        common_name: "Hyacinth",
        latin_name: "genus Hyacinthus", 
        watering_schedule: "Needs Constant Watering So That the Soil Stays Wet",
        soil_type: "Loose and Well Drained Soils Required",
        light_req: "Needs a Good and Strong Light Source",
        fertilizer_req: "Feed With a Weak Solution Every Third Watering",
        space_req: "N/A",
        indoor_outdoor: "Both",
        pest_info: "Common Pests: Small Insects and Rodents",
        pet_care: "Only Plant Bulbs are Toxic", 
        user_id: null
    },
    {
        id: 5, 
        common_name: "Cucumber",
        latin_name: "Cucumis sativus", 
        watering_schedule: "About 1 in of Water a Week ",
        soil_type: "Needs Warm and Well Drained Soil with a Neutral pH",
        light_req: "Abundant and Direct Sunlighgt",
        fertilizer_req: "Requires Regular Feedings - Frequency Depends on Grow Area",
        space_req: "Plant Seedlings about 36 to 60 in Apart, Vines Require a Trellis",
        indoor_outdoor: "Outdoor",
        pest_info: "Common Pests: Slugs and Beetles",
        pet_care: "N/A", 
        user_id: null
    },
    {
        id: 6,
        common_name: "Tomatoes",
        latin_name: "Solanum lycopersicum", 
        watering_schedule: "About 1 in of Water a Week ",
        soil_type: "Needs Warm and Well Drained Soil with a Slightly Acidic pH",
        light_req: "Abundant and Direct Sunlight",
        fertilizer_req: "Requires Regular Feedings During Growing Season",
        space_req: "Plant Seedlings Need to Be Evenly Spaced Apart, Vines Require a Trellis",
        indoor_outdoor: "Outdoor",
        pest_info: "Common Pests: Mites, Slugs, and Beetles",
        pet_care: "N/A", 
        user_id: null
    },
    {
        id: 7,
        common_name: "Butternut Squash",
        latin_name: "Cucurbita moschata 'Butternut'", 
        watering_schedule: "About 1 in of Water a Week ",
        soil_type: "Needs Warm and Well Drained Soil With Compost Introduced",
        light_req: "Abundant and Direct Sunlight",
        fertilizer_req: "Requires Regular Feedings, Continuous Release Fertilizer is Recommended",
        space_req: "Need Sufficient Space to Allow for Broad Leaves and Minimize Cooling Effect",
        indoor_outdoor: "Outdoor",
        pest_info: "Common Pests: Squash Vine Borers, Squash Bugs, and Cucumber Beetles",
        pet_care: "N/A", 
        user_id: null
    },
    {
        id: 8,
        common_name: "Boston Fern",
        latin_name: "Nephrolepis exaltata", 
        watering_schedule: "Enough to Keep the Soils Constantly Moist (At Least Once a Week)",
        soil_type: "Needs a Light, Moist and Well Draining Soil",
        light_req: "A Bright Spot Away From Harsh Sunlight",
        fertilizer_req: "Use a General Purpose Fertilizer Once Every Couple Months",
        space_req: "Space Required for Rapid and Regular Growth, Can Grow Quite Tall",
        indoor_outdoor: "Indoor",
        pest_info: "Common Pests: Caterpillars, Mealybugs, False Spider Mites, Scales and Thrips",
        pet_care: "N/A", 
        user_id: null
    },
    {
        id: 9,
        common_name: "Croton",
        latin_name: "Codiaeum variegatum pictum", 
        watering_schedule: "Enough to Keep the Soils Constantly Moist (At Least Once a Week)",
        soil_type: "Needs a Light, Moist and Well Draining Soil",
        light_req: "A Bright Spot Away From Harsh Sunlight",
        fertilizer_req: "Use a General Purpose Fertilizer Once Every Couple Months",
        space_req: "Space Required for Rapid and Regular Growth, Can Grow Quite Tall",
        indoor_outdoor: "Indoor",
        pest_info: "Common Pests: Caterpillars, Mealybugs, False Spider Mites, Scales and Thrips",
        pet_care: "N/A", 
        user_id: null
    },
    {
        id: 10,
        common_name: "Jasmine",
        latin_name: "Jasminum Polyanthum", 
        watering_schedule: "Frequent Watering to Keep Soil Moist at All Times",
        soil_type: "Needs a Sandy, Moist and Well Draining Soil",
        light_req: "A Bright Spot With Some Direct Sunlight",
        fertilizer_req: "Use Liquid Feed Every Couple of Weeks from late Spring to Late Autumn",
        space_req: "Space Required for Rapid and Regular Growth, Can Grow Quite Tall",
        indoor_outdoor: "Indoor Prefered During Cooler Months",
        pest_info: "Common Pests: Whiteflies, Mites, and Scales",
        pet_care: "N/A", 
        user_id: null
    },
    {
        id: 11,
        common_name: "Cyclamen",
        latin_name: "Cyclamen Persicum", 
        watering_schedule: "Enough to Keep the Soils Constantly Moist (At Least Once a Week)",
        soil_type: "Needs a Poor and Well Draining Soil",
        light_req: "A Bright Spot Away From Direct Sunlight",
        fertilizer_req: "Use a Small Amount of General Fertilizer Once Every Couple Weeks",
        space_req: "On Average Needs About 30 cm of Growing Room",
        indoor_outdoor: "Indoor",
        pest_info: "Common Pests: Mites and Spider Mites",
        pet_care: "The Tubers and Corns Can Be Toxic When Consumed", 
        user_id: null
    },
    {
        id: 12,
        common_name: "Leopard Lily",
        latin_name: "Dieffenbachia", 
        watering_schedule: "Try to Dry the Soil a Bit Between Waterings (At Least Once a Week)",
        soil_type: "Needs a Light, Moist and Well Draining Soil",
        light_req: "A Bright Spot Away From Harsh Sunlight",
        fertilizer_req: "Use a Half Strength Feed About Every Month",
        space_req: "Tends to Grow Based on the Size of Its Pot",
        indoor_outdoor: "Indoor",
        pest_info: "Common Pests: Red Spider Mites and Aphids",
        pet_care: "Highly Poisonous if Consumed", 
        user_id: null
    },
    {
        id: 13,
        common_name: "Ghost Echeveria",
        latin_name: "Echeveria", 
        watering_schedule: "Needs an Occasional Deep Watering",
        soil_type: "Needs a Well Draining Soil",
        light_req: "A Bright Spot With Some Direct Sunlight",
        fertilizer_req: "Use a Diluted Liquid Fertilizer Once a Month",
        space_req: "N/A",
        indoor_outdoor: "Both",
        pest_info: "Common Pests: Mealybugs, Spider Mites, and Scales",
        pet_care: "N/A", 
        user_id: null
    },
    {
        id: 14,
        common_name: "Gerbera",
        latin_name: "Gerbera Jamesonii", 
        watering_schedule: "About Once or Twice a Week",
        soil_type: "Needs a Slightly Acidic and Well Draining Soil",
        light_req: "A Bright Spot Away From Harsh Sunlight",
        fertilizer_req: "Use a Diluted Liquid Fertilizer Once a Month",
        space_req: "On Average, Allow for About 45 cm of Growth",
        indoor_outdoor: "Both",
        pest_info: "Common Pests: Whiteflies, Aphids, Spider Mites, and Thrips",
        pet_care: "N/A", 
        user_id: null
    },
    {
        id: 15,
        common_name: "Hippeastrum",
        latin_name: "Hippeastrum", 
        watering_schedule: "Enough to Keep the Soils Constantly Moist (At Least Once a Week)",
        soil_type: "Needs an Enriched and Well Draining Soil",
        light_req: "A Bright Spot Away From Harsh Sunlight",
        fertilizer_req: "Use a General Purpose Fertilizer Once Every Couple Weeks",
        space_req: "Allow for Up to About 75 cm of Growth",
        indoor_outdoor: "Outdoor",
        pest_info: "Common Pests: Mealybugs and Aphids",
        pet_care: "Slightly Toxic, Highest Concentration Found in the Bulb", 
        user_id: null
    },
    {
        id: 16,
        common_name: "Hurricane Plant",
        latin_name: "Monstera deliciosa", 
        watering_schedule: "Wait Until Soil is Almost Dry Between Waterings",
        soil_type: "Needs a Moist and Well Draining Soil",
        light_req: "A Bright Spot Away From Harsh Sunlight",
        fertilizer_req: "Use a General Purpose Fertilizer Once Every Month",
        space_req: "Space Required for Rapid and Regular Growth, Can Grow Quite Tall",
        indoor_outdoor: "Both",
        pest_info: "Common Pests: Whiteflies, Aphids, and Spider Mites",
        pet_care: "Both the Leaves and the Roots of this Plant are Toxic", 
        user_id: null
    },
    {
        id: 17,
        common_name: "Peace Lily",
        latin_name: "Spathiphyllum", 
        watering_schedule: "Enough to Keep the Soils Constantly Moist (At Least Once a Week)",
        soil_type: "Needs a Moist and Well Draining Soil",
        light_req: "A Bright Spot Away From Harsh Sunlight",
        fertilizer_req: "Use a Weak Fertilizer Once Every Couple of Weeks",
        space_req: "Allow for Growth of about 45 cm in Height",
        indoor_outdoor: "Indoor",
        pest_info: "Common Pests: Mealybugs, Aphids, and Spider Mites",
        pet_care: "Mildly Toxic and Irritable When Consumed By Pets", 
        user_id: null
    },
    {
        id: 18,
        common_name: "Pot Mum",
        latin_name: "Chrysanthemum", 
        watering_schedule: "Enough to Keep the Soils Constantly Damp (At Least Twice a Week)",
        soil_type: "Needs a Enriched, Moist, and Well Draining Soil",
        light_req: "A Bright Spot with Constant Sunlight",
        fertilizer_req: "Use a General Purpose Fertilizer Once Every Month",
        space_req: "Allow for Up to 30 cm in Both Height and Spread",
        indoor_outdoor: "Both",
        pest_info: "Common Pests: Aphids",
        pet_care: "Mildly Toxic and Irritable When Consumed By Pets", 
        user_id: null
    },
    {
        id: 19,
        common_name: "Madagascar Jewel",
        latin_name: "Euphorbia leuconeura", 
        watering_schedule: "water deeply, then allow the soil to dry before watering again",
        soil_type: "Needs a Light, Moist and Well Draining Soil",
        light_req: "A Bright Spot With Sunlight",
        fertilizer_req: "Use a Light Fertilizer During the Growing Season",
        space_req: "Space Required for Rapid and Regular Growth, Can Grow Quite Tall with Support",
        indoor_outdoor: "Indoor",
        pest_info: "Common Pests: Mealybugs",
        pet_care: "Mildly Toxic and Irritable When Consumed By Pets", 
        user_id: null
    },
    {
        id: 20,
        common_name: "Spider Plant",
        latin_name: "Chlorophytum", 
        watering_schedule: "Enough to Keep the Soils Constantly Moist (At Least Once a Week)",
        soil_type: "Needs a Loamy, Moist and Well Draining Soil",
        light_req: "A Bright Spot Away From Direct Sunlight",
        fertilizer_req: "Use a General Purpose Fertilizer Once a Month",
        space_req: "N/A",
        indoor_outdoor: "Indoor",
        pest_info: "Common Pests: Whiteflies, Aphids, Mealybugs, and Spider Mites",
        pet_care: "N/A", 
        user_id: null
    },

]

const seedPlant = () => Plant.bulkCreate(plantData);

module.exports = seedPlant;